version: '3.7'
services:
    webapp:
        image: nginx
        volumes:
            -  type: bind
               source: ./dist
               target: /usr/share/nginx/html
               read_only: true
        ports:
            - '8080:80'
